snd-soc-cs35l41-objs := cs35l41.o cs35l41-tables.o
snd-soc-cs35l41-spi-objs := cs35l41-spi.o
obj-$(CONFIG_SND_SOC_CS35L41)		+= snd-soc-cs35l41.o
obj-$(CONFIG_SND_SOC_CS35L41_SPI)	+= snd-soc-cs35l41-spi.o
